[package]
name = "env-variable-secrets-scanner-policy"
version = "0.1.2"
authors = ["raulcabello <raul.cabello@suse.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
k8s-openapi = { version = "0.16.0", default_features = false, features = ["v1_24"] }
kubewarden-policy-sdk = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
encoding = "0.2.33"
base64 = "0.13.1"
#TODO replace once rusty-hog-scanner is available upstream
rusty_hog_scanner = { git = "https://github.com/raulcabello/rusty-hog/", revision="981052cc194b25b881acc089e806799d58d97637" }
